# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 675)
        MainWindow.setStyleSheet("#MainWindow{border-image:url(./bg.jpg);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 580, 101, 41))
        self.pushButton.setStyleSheet("QPushButton{color:black}\n"
"QPushButton:hover{color:red}\n"
"QPushButton{background-color:lightgreen}\n"
"QPushButton{border:2px}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{padding:2px 4px}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 580, 101, 41))
        self.pushButton_2.setStyleSheet("QPushButton{color:black}\n"
"QPushButton:hover{color:red}\n"
"QPushButton{background-color:lightgreen}\n"
"QPushButton{border:2px}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{padding:2px 4px}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 891, 501))
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 580, 101, 41))
        self.pushButton_3.setStyleSheet("QPushButton{color:black}\n"
"QPushButton:hover{color:red}\n"
"QPushButton{background-color:lightgreen}\n"
"QPushButton{border:2px}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{padding:2px 4px}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 580, 101, 41))
        self.pushButton_4.setStyleSheet("QPushButton{color:black}\n"
"QPushButton:hover{color:red}\n"
"QPushButton{background-color:lightgreen}\n"
"QPushButton{border:2px}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{padding:2px 4px}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 580, 91, 41))
        self.pushButton_5.setStyleSheet("QPushButton{color:black}\n"
"QPushButton:hover{color:red}\n"
"QPushButton{background-color:lightgreen}\n"
"QPushButton{border:2px}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{padding:2px 4px}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(790, 580, 91, 41))
        self.pushButton_6.setStyleSheet("QPushButton{color:black}\n"
"QPushButton:hover{color:red}\n"
"QPushButton{background-color:lightblue}\n"
"QPushButton{border:2px}\n"
"QPushButton{border-radius:10px}\n"
"QPushButton{padding:2px 4px}")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Substation"))
        self.pushButton.setText(_translate("MainWindow", "缺陷检测"))
        self.pushButton_2.setText(_translate("MainWindow", "表计识别"))
        self.pushButton_3.setText(_translate("MainWindow", "识别批量演示"))
        self.pushButton_4.setText(_translate("MainWindow", "检测批量演示"))
        self.pushButton_5.setText(_translate("MainWindow", "清空界面"))
        self.pushButton_6.setText(_translate("MainWindow", "退出"))
